[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol = "GcB56zjFUweTEBKzRH3PmsnCErqyCFoaBrQ9AzgK7wSC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
